export const data = {
  products: [
    {
      id: "1",
      name: "Women's pants",
      category: "trousers",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "Dior",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 3,
    },
    {
      id: "2",
      name: "Women's jean",
      category: "trousers",
      image: "/images/product-2.jpg",
      price: 90,
      brand: "Balenciaga",
      rating: 3,
      numReviews: 7,
      description: "high quality product",
      countInStock: 2,
    },
    {
      id: "3",
      name: "Pull",
      category: "clothes",
      image: "/images/product-3.jpg",
      price: 200,
      brand: "Nike",
      rating: 5,
      numReviews: 15,
      description: "high quality product",
      countInStock: 0,
    },
    {
      id: "4",
      name: "tunics",
      category: "clothes",
      image: "/images/product-4.jpg",
      price: 250,
      brand: "Dior",
      rating: 3.5,
      numReviews: 8,
      description: "high quality product",
      countInStock: 7,
    },
    {
      id: "5",
      name: "Corduroy trousers",
      category: "trousers",
      image: "/images/product-5.jpg",
      price: 80,
      brand: "Adidas",
      rating: 7.5,
      numReviews: 11,
      description: "high quality product",
      countInStock: 0,
    },
    {
      id: "6",
      name: "Women's big pant's",
      category: "trousers",
      image: "/images/product-6.jpg",
      price: 140,
      brand: "Dior",
      rating: 5.5,
      numReviews: 13,
      description: "high quality product",
      countInStock: 10,
    },
  ],
};

export default data;
